# Generated by Django 5.2.4 on 2025-11-30
# Add profile_type field and create HLS Stream Profiles

from django.db import migrations, models


def create_hls_stream_profiles(apps, schema_editor):
    """Create the locked HLS Proxy and HLS FFmpeg stream profiles."""
    StreamProfile = apps.get_model("core", "StreamProfile")
    UserAgent = apps.get_model("core", "UserAgent")

    # Get the default user agent (TiviMate)
    default_user_agent = UserAgent.objects.filter(name="TiviMate").first()
    user_agent_id = default_user_agent.id if default_user_agent else None

    # HLS Proxy - Similar to Proxy but for HLS output (passthrough, no transcoding)
    # This is used when the source is already an HLS stream that just needs to be served
    StreamProfile.objects.get_or_create(
        name="HLS Proxy",
        defaults={
            "command": "",
            "parameters": "",
            "profile_type": "hls",
            "locked": True,
            "is_active": True,
            "user_agent_id": user_agent_id,
        }
    )

    # HLS FFmpeg - Mirrors the ffmpeg profile but outputs HLS instead of pipe:1
    # Uses {hlsOutputPath} placeholder which will be replaced with the HLS segment output path
    # HLS-specific parameters:
    #   -f hls: Output format HLS
    #   -hls_time 4: 4-second segments
    #   -hls_list_size 5: Keep 5 segments in playlist
    #   -hls_flags delete_segments+append_list: Delete old segments, append to playlist
    #   -hls_segment_filename: Pattern for segment filenames
    StreamProfile.objects.get_or_create(
        name="HLS FFmpeg",
        defaults={
            "command": "ffmpeg",
            "parameters": "-user_agent {userAgent} -i {streamUrl} -c copy -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments+append_list -hls_segment_filename {hlsOutputPath}/segment_%05d.ts {hlsOutputPath}/stream.m3u8",
            "profile_type": "hls",
            "locked": True,
            "is_active": True,
            "user_agent_id": user_agent_id,
        }
    )

    # Update existing profiles to have profile_type = 'ts' (they already default to this)
    # This is just to be explicit
    StreamProfile.objects.filter(name__in=["ffmpeg", "streamlink", "Proxy", "Redirect"]).update(
        profile_type="ts"
    )


def reverse_migration(apps, schema_editor):
    """Remove the HLS stream profiles."""
    StreamProfile = apps.get_model("core", "StreamProfile")
    StreamProfile.objects.filter(name__in=["HLS Proxy", "HLS FFmpeg"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_systemevent_event_type'),
    ]

    operations = [
        # Add profile_type field
        migrations.AddField(
            model_name='streamprofile',
            name='profile_type',
            field=models.CharField(
                choices=[('ts', 'MPEG-TS Output'), ('hls', 'HLS Output')],
                default='ts',
                help_text="Output type: 'ts' for MPEG-TS (pipe:1), 'hls' for HLS file output",
                max_length=10,
            ),
        ),
        # Create HLS profiles
        migrations.RunPython(create_hls_stream_profiles, reverse_code=reverse_migration),
    ]

