# Generated by Django 5.2.4 on 2025-11-30
# Update HLS FFmpeg profile with reconnection options

from django.db import migrations


def update_hls_ffmpeg_profile(apps, schema_editor):
    """Update the HLS FFmpeg profile to include reconnection options."""
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Update the HLS FFmpeg profile with reconnection options
    StreamProfile.objects.filter(
        name="HLS FFmpeg",
        locked=True
    ).update(
        parameters="-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -user_agent {userAgent} -i {streamUrl} -c copy -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments+append_list -hls_segment_filename {hlsOutputPath}/segment_%05d.ts {hlsOutputPath}/stream.m3u8"
    )


def reverse_migration(apps, schema_editor):
    """Revert to the old HLS FFmpeg profile parameters."""
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    StreamProfile.objects.filter(
        name="HLS FFmpeg",
        locked=True
    ).update(
        parameters="-user_agent {userAgent} -i {streamUrl} -c copy -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments+append_list -hls_segment_filename {hlsOutputPath}/segment_%05d.ts {hlsOutputPath}/stream.m3u8"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_hls_stream_profiles'),
    ]

    operations = [
        migrations.RunPython(update_hls_ffmpeg_profile, reverse_code=reverse_migration),
    ]

