# Generated by Django 5.2.4 on 2025-12-01
# Remove reconnect flags from HLS FFmpeg profile - Dispatcharr core handles reconnection

from django.db import migrations


def remove_reconnect_flags(apps, schema_editor):
    """Remove reconnect flags from HLS FFmpeg profile.
    
    The reconnect flags (-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5)
    conflict with Dispatcharr's core reconnection logic which handles stream failures
    and reconnection at a higher level. Having both causes issues.
    """
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    # Update the HLS FFmpeg profile to remove reconnection options
    StreamProfile.objects.filter(
        name="HLS FFmpeg",
        locked=True
    ).update(
        parameters="-user_agent {userAgent} -i {streamUrl} -c copy -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments+append_list -hls_segment_filename {hlsOutputPath}/segment_%05d.ts {hlsOutputPath}/stream.m3u8"
    )


def reverse_migration(apps, schema_editor):
    """Restore reconnect flags to HLS FFmpeg profile."""
    StreamProfile = apps.get_model("core", "StreamProfile")
    
    StreamProfile.objects.filter(
        name="HLS FFmpeg",
        locked=True
    ).update(
        parameters="-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -user_agent {userAgent} -i {streamUrl} -c copy -f hls -hls_time 4 -hls_list_size 5 -hls_flags delete_segments+append_list -hls_segment_filename {hlsOutputPath}/segment_%05d.ts {hlsOutputPath}/stream.m3u8"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_update_hls_ffmpeg_profile'),
    ]

    operations = [
        migrations.RunPython(remove_reconnect_flags, reverse_code=reverse_migration),
    ]

